[package]
name = "to_do-axtix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# web framework
actix-web = "^4"

# logging
log = "^0.4"
pretty_env_logger = "0.4.0"
